### ISSUE TITLE
About the number of cropped glint360k

### ISSUE THREAD

**Issue by jasonchenPJ** [tamerthamoqa/facenet-pytorch-glint360k#14]
Hi @tamerthamoqa
Thanks for your release of cropped glint360k dataset.
The number of dataset is 16,967,993, but actually there seem to be 17,091,657.

(https://github.com/deepinsight/insightface/tree/master/recognition/partial_fc)
![image](https://user-images.githubusercontent.com/47911137/123539567-fdd58200-d76c-11eb-9778-27e16d940284.png)

Is it caused by MTCNN detection?
Thanks

**Comment by tamerthamoqa** [comment]
Hello @jasonchenPJ 

Yes, the MTCNN [script](https://github.com/davidsandberg/facenet/blob/master/src/align/align_dataset_mtcnn.py) I used ignores images where the MTCNN model failed to detect a face or had more than one face in the image since I left the '--detect_multiple_faces' argument parameter as False.
